name: Latest Blog Posts
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme-with-blog-posts:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pull in latest blog posts
        uses: iamprincejkc/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/iamprincejkc"
