name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: iamprincejkc/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/iamprincejkc"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
